using Newtonsoft.Json;

using SkillMap.Business.RoadmapsWorkspace.Features.WorkspaceEvents.AddLearningItem;

namespace SkillMap.Api.RoadmapsWorkspace.WorkspaceEvents.AddLearningItem;

public class AddLearningItemRequest
{
    [JsonProperty("id")]
    public string Id { get; set; } // todo: remove this property after client is updated to not send it, since id will be generated by server

    [JsonProperty("title")]
    public string Title { get; set; }
    [JsonProperty("description")]
    public string Description { get; set; }
    [JsonProperty("status")]
    public string Status { get; set; }
    [JsonProperty("clientWorkspaceVersion")]
    public int ClientWorkspaceVersion { get; set; }

    public AddLearningItemCommand ToCommand(long userRoadmapId)
        => new (userRoadmapId, Id, Title, Description, Status, ClientWorkspaceVersion);
}

