name: Build frontend

on:
  push:
    branches: ["main"]
    paths:
      - "frontend/skill-map/**"
      - ".github/workflows/build-frontend.yaml"
  pull_request:
    branches: ["main"]
    paths:
      - "frontend/skill-map/**"
      - ".github/workflows/build-frontend.yaml"
  workflow_call:

jobs:
  frontend-build:
    name: Install, lint & build
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./frontend/skill-map

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: "yarn"
          cache-dependency-path: frontend/skill-map/yarn.lock

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Lint
        run: yarn lint

      - name: Build
        run: yarn build
